config/routes.rb
Rails.application.routes.draw do
  resources :cocktails do
    resources :doses, only: [:index, :new, :show, :create]
end

  resources :doses, only: [:destroy]

  root 'cocktails#index'
end

  # root 'controller#action'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
	has_many :doses, dependent: :destroy 
	has_many :ingredients, :through => :doses
	validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :ingredient, presence: true
  validates :cocktail, presence: true, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
	has_many :doses
	validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  # GET /cocktails
  def index
    @cocktails = Cocktail.all
  end

  # GET /cocktails/1
  def show
  end

  # GET /cocktails/new
  def new
    @cocktail = Cocktail.new
  end

  # GET /cocktails/1/edit
  def edit
  end

  # POST /cocktails
  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to @cocktail, notice: 'Cocktail was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /cocktails/1
  def update
    if @cocktail.update(cocktail_params)
      redirect_to @cocktail, notice: 'Cocktail was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /cocktails/1
  def destroy
    @cocktail.destroy
    redirect_to cocktails_url, notice: 'Cocktail was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cocktail_params
      params.require(:cocktail).permit(:name)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
	before_action :set_cocktail, only: [:index, :show, :new, :create]

	def index
		@doses = @cocktail.doses
	end

	def show
		@dose = Dose.find(params[:id])
	end

	def new
		@ingredients = Ingredient.order(:name)
		@dose = Dose.new
	end

	def create
		@dose = Dose.new(dose_params)
		@dose.cocktail = @cocktail
		if @dose.save
			redirect_to cocktail_path(@cocktail)
		else
			render :new
		end
	end

	def destroy
		@dose = Dose.find(params[:id])
		@dose.destroy
		redirect_to cocktail_path(@dose.cocktail.id)
	end


	private

	def dose_params
		params.require(:dose).permit(:description, :ingredient_id)
	end

	def set_cocktail
		@cocktail = Cocktail.find(params[:cocktail_id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/cocktails/_form.html.erb
<%= form_with(model: cocktail, local: true) do |form| %>
  <% if cocktail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cocktail.errors.count, "error") %> prohibited this cocktail from being saved:</h2>

      <ul>
      <% cocktail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :cocktail_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Editing Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Show', @cocktail %> |
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cocktails</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cocktails.each do |cocktail| %>
      <tr>
        <td><%= cocktail.name %></td>
        <td><%= link_to 'Show', cocktail %></td>
        <td><%= link_to 'Edit', edit_cocktail_path(cocktail) %></td>
        <td><%= link_to 'Destroy', cocktail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cocktail', new_cocktail_path %>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cocktail.name %>
</p>

<%= link_to 'Edit', edit_cocktail_path(@cocktail) %> |
<%= link_to 'Back', cocktails_path %>

app/views/doses/edit.html.erb
<h1>Doses#edit</h1>
<p>Find me in app/views/doses/edit.html.erb</p>

app/views/doses/index.html.erb
<h1>Doses#index</h1>
<hr>
<%= link_to "Back to Cocktail", cocktail_path(@doses.first.cocktail_id), class: "btn btn-primary" %>
<hr>
<% @doses.each do |dose| %>
<p><%= dose.ingredient.name %></p>
<p><%= link_to dose.description, cocktail_dose_path(@cocktail, dose)  %></p>
<% end %>
<hr>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<hr>
<hr>
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :ingredient_id, collection: @ingredients %>
  <%= f.input :description %>
  <%= f.submit "Add Dose", class: "btn btn-primary" %>
<% end %>
<hr>

app/views/doses/show.html.erb
<h1>Doses#show</h1>
<hr>
<p><%= link_to "Back to #{@cocktail.name}", cocktail_path(@cocktail), class: "btn btn-primary" %></p>
<hr>
<p><%= "#{@dose.description} of #{@dose.ingredient.name}" %></p>
<hr>
<%= link_to "Delete", dose_path(@dose),
      method: :delete,
      data: { confirm: "Are you sure?", }, class: "btn btn-danger" %>
      

app/views/layouts/_navbar_wagon.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>RailsMisterCocktail</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>

<body>
	<%= yield %>
</body>
</html>